---
# Sparta app deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-sparta-app-deployment
spec:
  selector:
    matchLabels:
      app: spring-sparta-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-sparta-app
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command:
          - sh
          - -c
          - >
            until nc -z java-app-db-svc 3306; do
              echo "Waiting for database...";
              sleep 5;
            done;
      containers:
      - name: spring-sparta-app
        image: gina98/java-test-app
        Image ID: sha256:183ab2c0af7be57c6197a21d6dbf63bf4ec895dc5a87e63c4db949273d48ed0d
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: jdbc:mysql://java-app-db-svc:3306/library
        - name: DB_USER
          value: gina98
        - name: DB_PASS
          value: Stok3s:12!
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: spring-sparta-app-service
  namespace: default
spec:
  ports:
  - nodePort: 30001
    port: 5000
    targetPort: 5000
  selector:
    app: spring-sparta-app
  type: NodePort
